### PR TITLE
Update RSS feed (among other things)

### PR DESCRIPTION
**Pull request by j-f1**
I’m happy to remove one or more of the commits if you don’t want them:

- cleanup: a3efab6 & ae54aa9
- include links to sources in the RSS feed (they were missing before): 5738f5b
- make the styles of the source links consistent; replace `<span class="small">` with `<small>`, remove duplicate CSS file 729ba2e
- Switch the RSS feed from displaying the news items as a list to putting each one in a paragraph, making it easier to read on a mobile device (since the list markup takes up precious horizontal space) 0aa8d19
- Add permalinks to the entries in the archive, so going to the article URL in the RSS feed works 8a56e88
  - Maybe switch the archive to link to each entry on a separate page so people can share entries they like without having to wait for the page to finish loading (esp. as the impeachment process drags on)

### CODE REVIEW

**Comment by j-f1** [comment]
@sinker have you had a chance to look at this yet? I’d like to get at least https://github.com/sinker/impeachment.fyi/commit/5738f5ba5845dd2438044bff01572de58054f32b included so I can see the original articles when using my RSS reader.

**Comment by miklb** [comment]
Re: archive, can you expand on your idea? The main issue is that the site uses a single data file so there’s not a way to generate daily archive pages with a permalink. Would require migrating to using posts/collections in Jekyll.

**Comment by j-f1** [comment]
It looks like it’s possible to use a [generator plugin](https://jekyllrb.com/docs/plugins/generators/) to dynamically generate pages. I could do this in a separate PR though, if you’d like.

**Comment by miklb** [comment]
Unless that is white listed by GitHub, that will also require using a build tool like GitHub Actions. Possibly something in Netlify.

I’m not advocating either way, just pointing out if not familiar. 

When I helped with the archive page I specifically looked to stay within the current constraints, but I’m willing to help if I can be of any to build a more robust system.

**Comment by j-f1** [comment]
It seems like this site [isn’t a GH Pages site](https://sinker.github.io/impeachment.fyi), and it appears to be [already deployed by Netlify](https://app.netlify.com/sites/eloquent-noyce-debe7b/deploys), so it should be OK to use non-whitelisted plugins.

**Comment by j-f1** [comment]
ping @sinker?

**Comment by j-f1** [comment]
@miklb @sinker What needs to be done to get this merged?

**Comment by miklb** [comment]
@j-f1 if you can rebase master onto this PR I will take a look tonight, but I don't have merge permissions.

**Comment by j-f1** [comment]
Done

**Comment by miklb** [comment]
@j-f1 I haven't forgotten, just had a 4 alarm emergency at work. Coming up for air today.

**Comment by miklb** [comment]
@j-f1 @sinker 

feed looks good to me, https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdeploy-preview-12--eloquent-noyce-debe7b.netlify.com

but the changes to the archive might need master merged in as it's currently broken https://deploy-preview-12--eloquent-noyce-debe7b.netlify.com/archive

Let me know if I can be of any help.

**Comment by miklb** [comment]
@j-f looks like a merge conflict in `archive.md` and I'm not seeing latest content https://deploy-preview-12--eloquent-noyce-debe7b.netlify.com/archive

**Comment by miklb** [comment]
oops, merge conflict seems gone, but content still missing since December. Otherwise seems fine to me.

**Comment by j-f1** [comment]
Fixed!

**Comment by miklb** [comment]
Awesome! Thanks for being patient with my fly by reviews. @sinker lgtm.

**Comment by j-f1** [comment]
Here’s how it looks in NetNewsWire:

Screenshot_2021-01-13 08 43 56

**Pull request closed without merging**
