### PR TITLE
Archive weekly

### PR DESCRIPTION
**Pull request by miklb**
Leaving this in draft mode but this pull request adds a Weekly Archive solution using pure Liquid syntax in the `archive.md` template.

Address #4 

Still to be done

- [x] Check markup validity

- [x] Styling on Headings

### CODE REVIEW

**Comment by dansinker** [comment]
OMG incredible. I'll check this out v soon. THANK YOU.

**Comment by miklb** [comment]
Cool. I’ll push another check so it says “last week” then “X weeks ago” otherwise it will drive me nuts

**Comment by miklb** [comment]
@sinker ok, now it says `This Week`, `Last Week` `X Weeks Ago`

Let me know if you see anything off.

**Comment by dansinker** [comment]
Wow, this is really amazing. How hard a fix is it to have Sunday be the start of a week though? The Weekend Addition is going to be a regular thing going forward and feels odd to end a week on a Sunday. I know language-wise I've been treating Monday more as the "start" of a week, but in a weekly archive bundle, it feels off.

**Comment by miklb** [comment]
Not hard. Just a change in the strftime to use the flag for week starts on Sunday

**Comment by miklb** [comment]
@sinker I just pushed the minor change to start weeks on Sunday. Let me know if that's what you had in mind.

**Comment by dansinker** [comment]
This is so amazing. Thank you so much!

**Comment by dansinker** [comment]
Ah hey, remember that little thing about this breaking in the new year? 

"-49 Weeks Ago"  is now how anything that isn't "this week" now reads in the update that I'll be pushing out this evening.

**Pull request merged**
